server:
  port: 8081

spring:
  #jackson:
    #default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/gestiondestock
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false